# Generated by Django 5.2.15 on 2026-07-14 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('projects', '0004_project_runtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('task_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('TEMPLATE', 'Template'), ('PROJECT_CUSTOM', 'Project custom')], default='TEMPLATE', max_length=32)),
                ('is_core', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=32)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.CharField(blank=True, default='', max_length=255)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.project')),
                ('responsible_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='identity.department')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.projectstage')),
            ],
            options={
                'db_table': 'work_items_task',
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('dependency_type', models.CharField(choices=[('HARD', 'Hard'), ('SOFT', 'Soft')], default='HARD', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='work_items.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='work_items.task')),
            ],
            options={
                'db_table': 'work_items_task_dependency',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='work_items__project_9674a9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsible_user', 'status'], name='work_items__respons_eaabe6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['stage', 'status'], name='work_items__stage_i_4aca73_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'task_code'), name='work_items_task_project_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'predecessor'), name='work_items_task_dependency_uniq'),
        ),
    ]
