# Generated by Django 5.2.15 on 2026-07-14 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('projects', '0004_project_runtime'),
        ('work_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deliverable_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('CORE_REQUIRED', 'Core required'), ('TEMPLATE_RECOMMENDED', 'Template recommended'), ('PROJECT_CUSTOM', 'Project custom')], max_length=32)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('CONTROLLED', 'Controlled'), ('EXEMPTED', 'Exempted'), ('VOIDED', 'Voided')], default='NOT_STARTED', max_length=32)),
                ('requires_professional_confirmation', models.BooleanField(default=True)),
                ('planned_due_at', models.DateTimeField(blank=True, null=True)),
                ('exemption_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compiler_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compiled_deliverables', to='work_items.task')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='projects.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='projects.projectstage')),
            ],
            options={
                'db_table': 'work_items_deliverable',
            },
        ),
        migrations.CreateModel(
            name='DeliverableRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked'), ('CONTROLLED', 'Controlled'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=32)),
                ('content_hash', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='work_items.deliverable')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverable_revisions', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_deliverable_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_items_deliverable_revision',
            },
        ),
        migrations.AddField(
            model_name='deliverable',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='work_items.deliverablerevision'),
        ),
        migrations.CreateModel(
            name='ProfessionalConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_professional_confirmations', to=settings.AUTH_USER_MODEL)),
                ('confirmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_confirmations', to=settings.AUTH_USER_MODEL)),
                ('deliverable_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='work_items.deliverablerevision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'work_items_professional_confirmation',
            },
        ),
        migrations.AddConstraint(
            model_name='deliverablerevision',
            constraint=models.UniqueConstraint(fields=('deliverable', 'revision_number'), name='work_items_deliverable_revision_uniq'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['project', 'status'], name='work_items__project_9e113a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['stage', 'status'], name='work_items__stage_i_ee0afc_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(fields=('project', 'deliverable_code'), name='work_items_deliverable_project_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='professionalconfirmation',
            index=models.Index(fields=['deliverable_revision', 'status'], name='work_items__deliver_e25722_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalconfirmation',
            index=models.Index(fields=['confirmer', 'status'], name='work_items__confirm_09a40e_idx'),
        ),
    ]
