# Generated by Django 5.2.15 on 2026-07-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0002_deliverables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('TEMPLATE', 'Template'), ('PROJECT_CUSTOM', 'Project custom'), ('MIGRATED_HISTORY', 'Migrated history')], default='TEMPLATE', max_length=32),
        ),
    ]
