# Generated by Django 5.2.15 on 2026-07-09 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0003_alter_projectcandidate_status_deferrecord_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_no', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('NEW_PRODUCT', 'New product'), ('PRODUCT_CHANGE', 'Product change')], max_length=24)),
                ('status', models.CharField(choices=[('INITIALIZING', 'Initializing'), ('ACTIVE', 'Active'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed'), ('CLOSED', 'Closed')], default='INITIALIZING', max_length=32)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='opportunities.projectcandidate')),
                ('deputy_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deputy_led_projects', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('product_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='products.productasset')),
                ('product_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='products.productdraft')),
            ],
            options={
                'db_table': 'projects_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('project_role', models.CharField(choices=[('LEADER', 'Leader'), ('DEPUTY', 'Deputy'), ('MEMBER', 'Member')], max_length=16)),
                ('active_from', models.DateTimeField()),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('appointed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_appointments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_project_member',
            },
        ),
        migrations.CreateModel(
            name='ProjectOpportunitySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_role', models.CharField(max_length=16)),
                ('linked_at', models.DateTimeField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_sources', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_sources', to='projects.project')),
            ],
            options={
                'db_table': 'projects_project_opportunity_source',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status', 'updated_at'], name='projects_pr_organiz_791cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['leader', 'status'], name='projects_pr_leader__6b9803_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'business_no'), name='projects_project_org_no_uniq'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'project_role'], name='projects_pr_project_254dff_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'active_from'], name='projects_pr_user_id_4295f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(condition=models.Q(('active_to__isnull', True)), fields=('project', 'user', 'project_role'), name='projects_member_active_uniq'),
        ),
        migrations.AddIndex(
            model_name='projectopportunitysource',
            index=models.Index(fields=['opportunity', 'linked_at'], name='projects_pr_opportu_35b27f_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectopportunitysource',
            constraint=models.UniqueConstraint(fields=('project', 'opportunity'), name='projects_opportunity_source_uniq'),
        ),
    ]
