# Generated by Django 5.2.15 on 2026-07-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectmember',
            name='projects_member_active_uniq',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='active_role_key',
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
    ]
