# Generated by Django 5.2.15 on 2026-07-14 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0005_remove_opportunitymember_opportunities_member_active_uniq_and_more'),
        ('products', '0010_attribute_group_assigned_confirmer'),
        ('projects', '0003_product_profile_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects_project_template_snapshot',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='actual_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='template_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='configuration.configurationsnapshot'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INITIALIZING', 'Initializing'), ('ACTIVE', 'Active'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed'), ('PUBLISH_PENDING_REPAIR', 'Publish pending repair'), ('OPERATING', 'Operating'), ('CLOSED', 'Closed')], default='INITIALIZING', max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('stage_code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('sequence_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('ACTIVE', 'Active'), ('READY_FOR_GATE', 'Ready for gate'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed')], default='NOT_STARTED', max_length=32)),
                ('handling_mode', models.CharField(choices=[('EXECUTE', 'Execute'), ('REUSE', 'Reuse'), ('SIMPLIFY', 'Simplify'), ('EXEMPT', 'Exempt'), ('NOT_APPLICABLE', 'Not applicable'), ('PARALLEL', 'Parallel')], default='EXECUTE', max_length=32)),
                ('gate_code', models.CharField(blank=True, default='', max_length=64)),
                ('gate_type', models.CharField(blank=True, default='', max_length=16)),
                ('depends_on', models.JSONField(default=list)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='projects.project')),
            ],
            options={
                'db_table': 'projects_project_stage',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.projectstage'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status', 'current_stage'], name='projects_pr_organiz_bb379c_idx'),
        ),
        migrations.AddField(
            model_name='projecttemplatesnapshot',
            name='configuration_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_template_snapshots', to='configuration.configurationsnapshot'),
        ),
        migrations.AddField(
            model_name='projecttemplatesnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='projecttemplatesnapshot',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project_template_snapshot', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projecttemplatesnapshot',
            name='source_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_template_snapshots', to='configuration.configurationversion'),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['project', 'sequence_no'], name='projects_pr_project_96b20f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_8871dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.UniqueConstraint(fields=('project', 'stage_code'), name='projects_project_stage_code_uniq'),
        ),
    ]
