# Generated by Django 5.2.15 on 2026-07-15 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('projects', '0004_project_runtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('exception_type', models.CharField(choices=[('EXECUTE', 'Execute'), ('REUSE', 'Reuse'), ('SIMPLIFY', 'Simplify'), ('EXEMPT', 'Exempt'), ('NOT_APPLICABLE', 'Not applicable'), ('PARALLEL', 'Parallel')], max_length=32)),
                ('previous_mode', models.CharField(choices=[('EXECUTE', 'Execute'), ('REUSE', 'Reuse'), ('SIMPLIFY', 'Simplify'), ('EXEMPT', 'Exempt'), ('NOT_APPLICABLE', 'Not applicable'), ('PARALLEL', 'Parallel')], max_length=32)),
                ('requested_mode', models.CharField(choices=[('EXECUTE', 'Execute'), ('REUSE', 'Reuse'), ('SIMPLIFY', 'Simplify'), ('EXEMPT', 'Exempt'), ('NOT_APPLICABLE', 'Not applicable'), ('PARALLEL', 'Parallel')], max_length=32)),
                ('rationale', models.TextField()),
                ('evidence_summary', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_execution_exceptions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_exceptions', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_execution_exceptions', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_exceptions', to='projects.projectstage')),
            ],
            options={
                'db_table': 'projects_execution_exception',
            },
        ),
        migrations.AddField(
            model_name='projectstage',
            name='exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.executionexception'),
        ),
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('change_type', models.CharField(choices=[('MINOR', 'Minor'), ('IMPORTANT', 'Important'), ('RESOURCE_ESCALATION', 'Resource escalation')], max_length=32)),
                ('target_type', models.CharField(max_length=64)),
                ('target_public_id', models.UUIDField()),
                ('field_name', models.CharField(max_length=64)),
                ('before_value', models.TextField(blank=True, default='')),
                ('after_value', models.TextField(blank=True, default='')),
                ('impact_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('PENDING_CONFIRMATION', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING_CONFIRMATION', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_plan_changes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_changes', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_plan_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_plan_change',
            },
        ),
        migrations.CreateModel(
            name='EmergencyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject_summary', models.CharField(max_length=255)),
                ('pending_confirmation', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('initiator_roles_snapshot', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_emergency_executions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_executions', to='projects.project')),
            ],
            options={
                'db_table': 'projects_emergency_execution',
                'indexes': [models.Index(fields=['project', 'status'], name='projects_em_project_b0fe30_idx'), models.Index(fields=['due_at', 'status'], name='projects_em_due_at_7cb9bf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='executionexception',
            index=models.Index(fields=['project', 'status'], name='projects_ex_project_20939e_idx'),
        ),
        migrations.AddIndex(
            model_name='executionexception',
            index=models.Index(fields=['stage', 'status'], name='projects_ex_stage_i_09cd83_idx'),
        ),
        migrations.AddIndex(
            model_name='planchange',
            index=models.Index(fields=['project', 'status'], name='projects_pl_project_618c2c_idx'),
        ),
    ]
