# Generated by Django 5.2.15 on 2026-07-15 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0005_remove_opportunitymember_opportunities_member_active_uniq_and_more'),
        ('projects', '0005_execution_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='opportunities.projectcandidate'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('ACTIVE', 'Active'), ('READY_FOR_GATE', 'Ready for gate'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed'), ('MIGRATED_HISTORY', 'Migrated history')], default='NOT_STARTED', max_length=32),
        ),
        migrations.CreateModel(
            name='MigrationBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_project_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=200)),
                ('current_stage_code', models.CharField(max_length=32)),
                ('leader_display_name', models.CharField(blank=True, default='', max_length=128)),
                ('disposition', models.CharField(choices=[('CONTINUE', 'Continue'), ('ARCHIVE_ONLY', 'Archive only')], default='CONTINUE', max_length=32)),
                ('history_decision_summary', models.TextField(blank=True, default='')),
                ('plan_summary', models.JSONField(default=dict)),
                ('history_tasks', models.JSONField(default=list)),
                ('history_files', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='IMPORTED', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_migration_baselines', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'projects_migration_baseline',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='migration_baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='projects.migrationbaseline'),
        ),
        migrations.CreateModel(
            name='MigrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('batch_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('source_row_count', models.PositiveIntegerField(default=0)),
                ('accepted_row_count', models.PositiveIntegerField(default=0)),
                ('error_row_count', models.PositiveIntegerField(default=0)),
                ('row_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_migration_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'projects_migration_batch',
            },
        ),
        migrations.AddField(
            model_name='migrationbaseline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baselines', to='projects.migrationbatch'),
        ),
        migrations.AddConstraint(
            model_name='migrationbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'batch_key'), name='projects_migration_batch_org_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='migrationbaseline',
            constraint=models.UniqueConstraint(fields=('batch', 'external_project_id'), name='projects_migration_baseline_batch_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='migrationbaseline',
            constraint=models.UniqueConstraint(fields=('organization', 'external_project_id'), name='projects_migration_baseline_org_external_uniq'),
        ),
    ]
