# Generated by Django 5.2.15 on 2026-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_migration_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyexecution',
            name='confirmation_evidence',
            field=models.TextField(blank=True, default=''),
        ),
    ]
