# Generated by Django 5.2.15 on 2026-07-17 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('projects', '0008_migration_history_deliverables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationbaseline',
            name='confirm_idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='migrationbaseline',
            constraint=models.UniqueConstraint(fields=('organization', 'confirm_idempotency_key'), name='projects_migration_baseline_org_confirm_key_uniq'),
        ),
    ]
