# Generated by Django 5.2.15 on 2026-07-20 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('projects', '0009_alter_migrationbaseline_confirm_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationFileStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('staging_relpath', models.CharField(max_length=512, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('declared_mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_file_stages', to='projects.migrationbaseline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_migration_file_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_migration_file_stage',
                'indexes': [models.Index(fields=['organization', 'expires_at'], name='projects_mi_organiz_c47231_idx'), models.Index(fields=['claimed_baseline'], name='projects_mi_claimed_e1cc0d_idx')],
            },
        ),
    ]
