# Generated by Django 5.2.15 on 2026-07-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_migration_file_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationfilestage',
            name='staging_relpath',
            field=models.CharField(max_length=191, unique=True),
        ),
    ]
