# Generated by Django 5.2.15 on 2026-07-08 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageGateInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject_type', models.CharField(choices=[('OPPORTUNITY', 'Opportunity'), ('PROJECT_CANDIDATE', 'Project candidate')], max_length=32)),
                ('subject_public_id', models.UUIDField()),
                ('stage_code', models.CharField(choices=[('PROPOSAL_TO_CASE', 'Proposal to case'), ('CASE_TO_PROJECT', 'Case to project'), ('FIRST_LAUNCH', 'First launch'), ('PRODUCT_RETIREMENT', 'Product retirement')], max_length=32)),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DECIDED', 'Decided'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('primary_material_type', models.CharField(choices=[('PROPOSAL_VERSION', 'Proposal version'), ('CASE_ASSESSMENT', 'Case assessment')], max_length=32)),
                ('primary_material_public_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('previous_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_cycles', to='stage_gates.stagegateinstance')),
            ],
            options={
                'db_table': 'stage_gates_instance',
            },
        ),
        migrations.CreateModel(
            name='MajorGateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('management_conclusion', models.CharField(choices=[('APPROVED', 'Approved'), ('APPROVED_WITH_EXCEPTION', 'Approved with exception'), ('NEEDS_INFO', 'Needs info'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed')], max_length=32)),
                ('final_decision', models.CharField(choices=[('APPROVED', 'Approved'), ('APPROVED_WITH_EXCEPTION', 'Approved with exception'), ('NEEDS_INFO', 'Needs info'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed')], max_length=32)),
                ('has_conclusion_difference', models.BooleanField(default=False)),
                ('decision_summary', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('decided_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_decision_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_final_decisions', to=settings.AUTH_USER_MODEL)),
                ('management_conclusion_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_management_conclusions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('stage_gate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='stage_gates.stagegateinstance')),
            ],
            options={
                'db_table': 'stage_gates_major_decision',
            },
        ),
        migrations.CreateModel(
            name='GateMaterialReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('material_type', models.CharField(choices=[('PROPOSAL_VERSION', 'Proposal version'), ('CASE_ASSESSMENT', 'Case assessment')], max_length=32)),
                ('material_public_id', models.UUIDField()),
                ('locked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('stage_gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_references', to='stage_gates.stagegateinstance')),
            ],
            options={
                'db_table': 'stage_gates_material_reference',
            },
        ),
        migrations.AddIndex(
            model_name='stagegateinstance',
            index=models.Index(fields=['subject_type', 'subject_public_id', 'stage_code'], name='stage_gates_subject_60c087_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagegateinstance',
            constraint=models.UniqueConstraint(fields=('subject_type', 'subject_public_id', 'stage_code', 'cycle_number'), name='stage_gates_instance_cycle_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stagegateinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('primary_material_type', 'primary_material_public_id'), name='stage_gates_active_material_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gatematerialreference',
            constraint=models.UniqueConstraint(fields=('stage_gate', 'material_type', 'material_public_id'), name='stage_gates_material_ref_uniq'),
        ),
    ]
