# Generated by Django 5.2.15 on 2026-07-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_gates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stagegateinstance',
            name='stage_gates_active_material_uniq',
        ),
        migrations.AddField(
            model_name='stagegateinstance',
            name='open_material_key',
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
    ]
