# Generated by Django 5.2.15 on 2026-07-15 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('projects', '0005_execution_controls'),
        ('stage_gates', '0002_remove_stagegateinstance_stage_gates_active_material_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stagegateinstance',
            name='gate_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('MAJOR', 'Major')], default='MAJOR', max_length=16),
        ),
        migrations.AddField(
            model_name='stagegateinstance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_gates', to='projects.project'),
        ),
        migrations.AddField(
            model_name='stagegateinstance',
            name='project_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_gates', to='projects.projectstage'),
        ),
        migrations.AlterField(
            model_name='gatematerialreference',
            name='material_type',
            field=models.CharField(choices=[('PROPOSAL_VERSION', 'Proposal version'), ('CASE_ASSESSMENT', 'Case assessment'), ('PROJECT_STAGE', 'Project stage'), ('DELIVERABLE_REVISION', 'Deliverable revision'), ('DOCUMENT_VERSION', 'Document version')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stagegateinstance',
            name='primary_material_type',
            field=models.CharField(choices=[('PROPOSAL_VERSION', 'Proposal version'), ('CASE_ASSESSMENT', 'Case assessment'), ('PROJECT_STAGE', 'Project stage'), ('DELIVERABLE_REVISION', 'Deliverable revision'), ('DOCUMENT_VERSION', 'Document version')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stagegateinstance',
            name='stage_code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='stagegateinstance',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('READY', 'Ready'), ('SUBMITTED', 'Submitted'), ('NEEDS_INFO', 'Needs info'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed'), ('APPROVED', 'Approved'), ('DECIDED', 'Decided'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16),
        ),
        migrations.AlterField(
            model_name='stagegateinstance',
            name='subject_type',
            field=models.CharField(choices=[('OPPORTUNITY', 'Opportunity'), ('PROJECT_CANDIDATE', 'Project candidate'), ('PROJECT', 'Project')], max_length=32),
        ),
        migrations.CreateModel(
            name='GateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('submission_number', models.PositiveIntegerField()),
                ('snapshot_json', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('validation_result_json', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('stage_gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='stage_gates.stagegateinstance')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stage_gates_gate_submission',
            },
        ),
        migrations.CreateModel(
            name='GateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('result', models.CharField(choices=[('APPROVED', 'Approved'), ('APPROVED_WITH_EXCEPTION', 'Approved with exception'), ('NEEDS_INFO', 'Needs info'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed')], max_length=32)),
                ('decision_summary', models.TextField(blank=True, default='')),
                ('exception_rationale', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('decided_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normal_gate_decisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('stage_gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normal_decisions', to='stage_gates.stagegateinstance')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='stage_gates.gatesubmission')),
            ],
            options={
                'db_table': 'stage_gates_gate_decision',
            },
        ),
        migrations.AddField(
            model_name='stagegateinstance',
            name='current_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stage_gates.gatesubmission'),
        ),
        migrations.CreateModel(
            name='GateSubmissionMaterialReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('material_type', models.CharField(choices=[('PROPOSAL_VERSION', 'Proposal version'), ('CASE_ASSESSMENT', 'Case assessment'), ('PROJECT_STAGE', 'Project stage'), ('DELIVERABLE_REVISION', 'Deliverable revision'), ('DOCUMENT_VERSION', 'Document version')], max_length=32)),
                ('material_public_id', models.UUIDField()),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('locked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_references', to='stage_gates.gatesubmission')),
            ],
            options={
                'db_table': 'stage_gates_submission_material_reference',
            },
        ),
        migrations.AddConstraint(
            model_name='gatesubmission',
            constraint=models.UniqueConstraint(fields=('stage_gate', 'submission_number'), name='stage_gates_submission_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gatesubmission',
            constraint=models.UniqueConstraint(fields=('stage_gate', 'idempotency_key'), name='stage_gates_submission_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gatesubmissionmaterialreference',
            constraint=models.UniqueConstraint(fields=('submission', 'material_type', 'material_public_id'), name='stage_gates_submission_material_uniq'),
        ),
    ]
