# Generated by Django 5.2.15 on 2026-07-15 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_gates', '0003_execution_submissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorgatedecision',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('APPROVED_WITH_EXCEPTION', 'Approved with exception'), ('NEEDS_INFO', 'Needs info'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='majorgatedecision',
            name='final_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_final_decisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
