# Generated by Django 5.2.15 on 2026-07-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage_gates', '0005_majorgatedecision_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatematerialreference',
            name='material_type',
            field=models.CharField(choices=[('PROPOSAL_VERSION', 'Proposal version'), ('CASE_ASSESSMENT', 'Case assessment'), ('PROJECT_STAGE', 'Project stage'), ('DELIVERABLE_REVISION', 'Deliverable revision'), ('DOCUMENT_VERSION', 'Document version'), ('OPERATING_DATA_SNAPSHOT', 'Operating data snapshot'), ('RETIREMENT_PLAN', 'Retirement plan')], max_length=32),
        ),
        migrations.AlterField(
            model_name='gatesubmissionmaterialreference',
            name='material_type',
            field=models.CharField(choices=[('PROPOSAL_VERSION', 'Proposal version'), ('CASE_ASSESSMENT', 'Case assessment'), ('PROJECT_STAGE', 'Project stage'), ('DELIVERABLE_REVISION', 'Deliverable revision'), ('DOCUMENT_VERSION', 'Document version'), ('OPERATING_DATA_SNAPSHOT', 'Operating data snapshot'), ('RETIREMENT_PLAN', 'Retirement plan')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stagegateinstance',
            name='primary_material_type',
            field=models.CharField(choices=[('PROPOSAL_VERSION', 'Proposal version'), ('CASE_ASSESSMENT', 'Case assessment'), ('PROJECT_STAGE', 'Project stage'), ('DELIVERABLE_REVISION', 'Deliverable revision'), ('DOCUMENT_VERSION', 'Document version'), ('OPERATING_DATA_SNAPSHOT', 'Operating data snapshot'), ('RETIREMENT_PLAN', 'Retirement plan')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stagegateinstance',
            name='subject_type',
            field=models.CharField(choices=[('OPPORTUNITY', 'Opportunity'), ('PROJECT_CANDIDATE', 'Project candidate'), ('PROJECT', 'Project'), ('RETIREMENT_PLAN', 'Retirement plan')], max_length=32),
        ),
    ]
