# Generated by Django 5.2.15 on 2026-07-15 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('products', '0010_attribute_group_assigned_confirmer'),
        ('projects', '0005_execution_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('effective_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('source_decision_public_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_monitoring_scopes', to=settings.AUTH_USER_MODEL)),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_scopes', to='products.productversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_scopes', to='projects.project')),
            ],
            options={
                'db_table': 'operations_monitoring_scope',
                'constraints': [models.UniqueConstraint(fields=('project', 'source_decision_public_id'), name='operations_monitoring_scope_project_decision_uniq')],
            },
        ),
    ]
