# Generated by Django 5.2.15 on 2026-07-21 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('operations', '0001_initial'),
        ('products', '0010_attribute_group_assigned_confirmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinitionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metric_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('version_number', models.PositiveIntegerField()),
                ('value_type', models.CharField(max_length=32)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('source_field_codes', models.JSONField(default=list)),
                ('calculation_type', models.CharField(choices=[('SUM', 'Sum'), ('AVERAGE', 'Average'), ('LAST', 'Last'), ('RATIO', 'Ratio'), ('CONTROLLED_RULE', 'Controlled rule')], max_length=32)),
                ('aggregation_rule', models.JSONField(default=dict)),
                ('window_definition', models.JSONField(default=dict)),
                ('coverage_requirement', models.JSONField(default=dict)),
                ('controlled_rule_code', models.CharField(blank=True, default='', max_length=64)),
                ('parameters_json', models.JSONField(default=dict)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_definitions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metric_definitions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_metric_definition_version',
                'indexes': [models.Index(fields=['organization', 'metric_code', 'status'], name='ops_metric_code_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'metric_code', 'version_number'), name='operations_metric_def_org_code_ver_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scope_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SKU', 'SKU'), ('SKU_CHANNEL', 'SKU channel')], max_length=16)),
                ('scope_key', models.CharField(max_length=128)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_data_level', models.CharField(choices=[('PUBLIC_SUMMARY', 'Public summary'), ('INTERNAL', 'Internal'), ('PROJECT_CONTROLLED', 'Project controlled'), ('SENSITIVE_CONTROLLED', 'Sensitive controlled'), ('HIGHLY_SENSITIVE', 'Highly sensitive')], default='SENSITIVE_CONTROLLED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_assignments', to='products.channelconfiguration')),
                ('monitoring_scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='operations.monitoringscope')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_assignments', to='products.productasset')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_assignments', to='products.sku')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_monitoring_assignment',
                'indexes': [models.Index(fields=['organization', 'supervisor', 'status', 'effective_from'], name='ops_mon_asg_sup_eff_idx'), models.Index(fields=['product', 'status'], name='ops_mon_asg_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('monitoring_scope', 'supervisor', 'scope_key', 'active_slot'), name='operations_monitoring_assignment_active_uniq')],
            },
        ),
    ]
