# Generated by Django 5.2.15 on 2026-07-21 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('integrations', '0003_operating_ingestion'),
        ('operations', '0002_monitoring_assignments_metric_definitions'),
        ('products', '0010_attribute_group_assigned_confirmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('period_granularity', models.CharField(max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('source_record_key', models.CharField(max_length=128)),
                ('fact_status', models.CharField(choices=[('VALID', 'Valid'), ('SUPERSEDED', 'Superseded'), ('INVALID', 'Invalid')], default='VALID', max_length=16)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_facts', to='integrations.ingestionbatch')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_facts', to='products.channelconfiguration')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_facts', to='operations.metricdefinitionversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_facts', to='products.sku')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_facts', to='integrations.datasource')),
            ],
            options={
                'db_table': 'operations_operating_fact',
            },
        ),
        migrations.CreateModel(
            name='ManualEffectiveValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('period_granularity', models.CharField(max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('reason', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', max_length=16)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_effective_values', to='products.channelconfiguration')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_effective_values_confirmed', to=settings.AUTH_USER_MODEL)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_effective_values', to='operations.metricdefinitionversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_effective_values', to='products.sku')),
                ('original_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_overrides', to='operations.operatingfact')),
            ],
            options={
                'db_table': 'operations_manual_effective_value',
            },
        ),
        migrations.AddIndex(
            model_name='operatingfact',
            index=models.Index(fields=['organization', 'sku', 'channel', 'metric_definition', 'period_start'], name='ops_fact_scope_period_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingfact',
            index=models.Index(fields=['source', 'source_record_key', 'fact_status'], name='ops_fact_source_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='operatingfact',
            constraint=models.UniqueConstraint(fields=('source', 'source_record_key', 'metric_definition', 'sku', 'channel', 'period_granularity', 'period_start', 'period_end', 'active_slot'), name='operations_operating_fact_active_uniq'),
        ),
        migrations.AddIndex(
            model_name='manualeffectivevalue',
            index=models.Index(fields=['organization', 'sku', 'channel', 'status'], name='ops_manual_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='manualeffectivevalue',
            constraint=models.UniqueConstraint(fields=('sku', 'channel', 'metric_definition', 'period_granularity', 'period_start', 'period_end', 'active_slot'), name='operations_manual_value_active_uniq'),
        ),
    ]
