# Generated by Django 5.2.15 on 2026-07-21 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('operations', '0003_operating_facts'),
        ('products', '0010_attribute_group_assigned_confirmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('grain_type', models.CharField(choices=[('SKU', 'SKU'), ('PRODUCT', 'Product')], max_length=16)),
                ('grain_id', models.UUIDField()),
                ('channel_key', models.CharField(default='ALL', max_length=64)),
                ('period_granularity', models.CharField(max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('NOT_COMPARABLE', 'Not comparable'), ('INSUFFICIENT', 'Insufficient')], default='OK', max_length=32)),
                ('coverage_rate', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('has_manual_value', models.BooleanField(default=False)),
                ('contributors_json', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField()),
                ('calculation_run_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metric_aggregates', to='products.channelconfiguration')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_aggregates', to='operations.metricdefinitionversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'operations_metric_aggregate',
                'indexes': [models.Index(fields=['organization', 'metric_definition', 'period_start', 'period_end'], name='ops_agg_org_metric_period_idx'), models.Index(fields=['organization', 'grain_type', 'grain_id', 'period_start'], name='ops_agg_grain_period_idx'), models.Index(fields=['organization', 'channel', 'period_start'], name='ops_agg_channel_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'grain_type', 'grain_id', 'channel_key', 'metric_definition', 'period_granularity', 'period_start', 'period_end'), name='operations_metric_aggregate_scope_uniq')],
            },
        ),
        migrations.CreateModel(
            name='OperatingDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(max_length=64)),
                ('scope_json', models.JSONField(default=dict)),
                ('periods_json', models.JSONField(default=list)),
                ('metric_codes', models.JSONField(default=list)),
                ('payload_json', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_data_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'operations_operating_data_snapshot',
                'indexes': [models.Index(fields=['organization', 'purpose', 'created_at'], name='ops_snapshot_org_purpose_idx')],
            },
        ),
    ]
