# Generated by Django 5.2.15 on 2026-07-21 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('operations', '0004_operating_aggregates_snapshots'),
        ('products', '0010_attribute_group_assigned_confirmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('rule_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('version_number', models.PositiveIntegerField()),
                ('metric_codes', models.JSONField(default=list)),
                ('evaluator_code', models.CharField(max_length=64)),
                ('parameters_json', models.JSONField(default=dict)),
                ('scope_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SKU', 'SKU'), ('SKU_CHANNEL', 'SKU channel')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_rules_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_rules_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_risk_rule_version',
            },
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scope_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SKU', 'SKU'), ('SKU_CHANNEL', 'SKU channel')], max_length=16)),
                ('scope_id', models.UUIDField()),
                ('scope_key', models.CharField(max_length=160)),
                ('period_granularity', models.CharField(default='QUARTER', max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VIEWED', 'Viewed'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], default='NEW', max_length=16)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('formula_snapshot', models.JSONField(default=dict)),
                ('coverage_status', models.CharField(choices=[('SUFFICIENT', 'Sufficient'), ('INSUFFICIENT', 'Insufficient')], default='SUFFICIENT', max_length=16)),
                ('closed_reason', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('display_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_signals', to='products.channelconfiguration')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_signals_closed', to=settings.AUTH_USER_MODEL)),
                ('data_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_signals', to='operations.operatingdatasnapshot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='operations.riskruleversion')),
            ],
            options={
                'db_table': 'operations_risk_signal',
            },
        ),
        migrations.CreateModel(
            name='SignalRecalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(max_length=128)),
                ('old_actual_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('new_actual_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('old_threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('new_threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('impact_summary', models.TextField()),
                ('calculated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalculations', to='operations.risksignal')),
                ('triggered_by_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signal_recalculations', to='operations.operatingfact')),
                ('triggered_by_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signal_recalculations', to='operations.manualeffectivevalue')),
            ],
            options={
                'db_table': 'operations_signal_recalculation',
            },
        ),
        migrations.AddIndex(
            model_name='riskruleversion',
            index=models.Index(fields=['organization', 'rule_code', 'status'], name='ops_risk_rule_code_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskruleversion',
            constraint=models.UniqueConstraint(fields=('organization', 'rule_code', 'version_number'), name='operations_risk_rule_org_code_ver_uniq'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['organization', 'status', 'period_start'], name='ops_rsig_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['organization', 'scope_key', 'period_start'], name='ops_rsig_scope_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='risksignal',
            constraint=models.UniqueConstraint(fields=('rule_version', 'scope_key', 'period_start', 'period_end'), name='operations_risk_signal_rule_scope_period_uniq'),
        ),
        migrations.AddIndex(
            model_name='signalrecalculation',
            index=models.Index(fields=['organization', 'signal', 'calculated_at'], name='ops_signal_recalc_signal_idx'),
        ),
    ]
