# Generated by Django 5.2.15 on 2026-07-21 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('operations', '0005_risk_rules_signals'),
        ('products', '0010_attribute_group_assigned_confirmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_no', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYZING', 'Analyzing'), ('OBSERVING', 'Observing'), ('ACTIONING', 'Actioning'), ('CONVERTED_TO_PROPOSAL', 'Converted to proposal'), ('RETIREMENT_REVIEW', 'Retirement review'), ('CLOSED', 'Closed')], default='PENDING', max_length=32)),
                ('source_type', models.CharField(choices=[('RISK_SIGNAL', 'Risk signal'), ('PRODUCT_PORTFOLIO_REVIEW', 'Product portfolio review'), ('QUALITY_COMPLIANCE', 'Quality compliance'), ('STRATEGIC', 'Strategic'), ('DIRECT', 'Direct')], max_length=32)),
                ('source_materials_json', models.JSONField(blank=True, default=dict)),
                ('phenomenon_summary', models.TextField()),
                ('recommendation_type', models.CharField(blank=True, choices=[('CONTINUE_OBSERVING', 'Continue observing'), ('ADJUST_PRICE', 'Adjust price'), ('ADJUST_CHANNEL', 'Adjust channel'), ('ADJUST_MARKET', 'Adjust market'), ('ADJUST_SUPPLY', 'Adjust supply'), ('ITERATE', 'Iterate'), ('SUSPEND', 'Suspend'), ('RETIRE', 'Retire'), ('CLOSE', 'Close')], default='', max_length=32)),
                ('target_review_at', models.DateTimeField(blank=True, null=True)),
                ('linked_opportunity_id', models.UUIDField(blank=True, null=True)),
                ('linked_project_id', models.UUIDField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operating_issues_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_issues_created', to=settings.AUTH_USER_MODEL)),
                ('data_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operating_issues', to='operations.operatingdatasnapshot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_issues_owned', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_issues', to='products.productasset')),
            ],
            options={
                'db_table': 'operations_operating_issue',
            },
        ),
        migrations.CreateModel(
            name='IssueSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('active_primary_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('linked_at', models.DateTimeField()),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_links', to='operations.risksignal')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_links', to='operations.operatingissue')),
            ],
            options={
                'db_table': 'operations_issue_signal',
            },
        ),
        migrations.CreateModel(
            name='IssueDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('recommendation_type', models.CharField(choices=[('CONTINUE_OBSERVING', 'Continue observing'), ('ADJUST_PRICE', 'Adjust price'), ('ADJUST_CHANNEL', 'Adjust channel'), ('ADJUST_MARKET', 'Adjust market'), ('ADJUST_SUPPLY', 'Adjust supply'), ('ITERATE', 'Iterate'), ('SUSPEND', 'Suspend'), ('RETIRE', 'Retire'), ('CLOSE', 'Close')], max_length=32)),
                ('action_summary', models.TextField()),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('materials_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_issue_decisions_made', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operating_issue_decisions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='operations.operatingissue')),
            ],
            options={
                'db_table': 'operations_issue_decision',
            },
        ),
        migrations.AddIndex(
            model_name='operatingissue',
            index=models.Index(fields=['organization', 'status', 'target_review_at'], name='ops_issue_status_review_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingissue',
            index=models.Index(fields=['organization', 'product', 'status'], name='ops_issue_product_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='operatingissue',
            constraint=models.UniqueConstraint(fields=('organization', 'business_no'), name='operations_issue_org_business_no_uniq'),
        ),
        migrations.AddIndex(
            model_name='issuesignal',
            index=models.Index(fields=['organization', 'issue', 'is_primary'], name='ops_issue_signal_issue_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuesignal',
            constraint=models.UniqueConstraint(fields=('signal', 'active_primary_slot'), name='operations_issue_signal_active_primary_uniq'),
        ),
        migrations.AddConstraint(
            model_name='issuesignal',
            constraint=models.UniqueConstraint(fields=('issue', 'signal'), name='operations_issue_signal_pair_uniq'),
        ),
        migrations.AddIndex(
            model_name='issuedecision',
            index=models.Index(fields=['organization', 'issue', 'decided_at'], name='ops_issue_decision_issue_idx'),
        ),
    ]
