# Generated by Django 5.2.15 on 2026-07-21 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('operations', '0006_operating_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingissue',
            name='linked_effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatingissue',
            name='linked_product_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IssueConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('conversion_type', models.CharField(choices=[('ITERATION_PROPOSAL', 'Iteration proposal')], max_length=32)),
                ('opportunity_public_id', models.UUIDField()),
                ('source_snapshot_json', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('converted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_conversions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='operations.operatingissue')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'operations_issue_conversion',
                'indexes': [models.Index(fields=['organization', 'opportunity_public_id'], name='ops_issue_conv_opp_idx')],
                'constraints': [models.UniqueConstraint(fields=('issue', 'conversion_type'), name='operations_issue_conversion_type_uniq'), models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='operations_issue_conversion_idem_uniq')],
            },
        ),
    ]
