# Generated by Django 5.2.15 on 2026-07-21 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('operations', '0007_issue_iteration_conversion'),
        ('products', '0011_sku_production_status_sku_production_stopped_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('scope_snapshot', models.JSONField(default=dict)),
                ('inventory_plan', models.JSONField(default=dict)),
                ('supply_contract_impact', models.JSONField(default=dict)),
                ('customer_market_plan', models.JSONField(default=dict)),
                ('replacement_plan', models.JSONField(default=dict)),
                ('coverage_gap_explanation', models.TextField(blank=True, default='')),
                ('document_version_public_id', models.UUIDField(blank=True, null=True)),
                ('document_version_hash', models.CharField(blank=True, default='', max_length=64)),
                ('stop_production_at', models.DateField(blank=True, null=True)),
                ('stop_sale_at', models.DateField(blank=True, null=True)),
                ('retire_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('PASSED', 'Passed'), ('EXECUTION_ERROR', 'Execution error')], default='DRAFT', max_length=24)),
                ('stage_gate_public_id', models.UUIDField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retirement_plans_created', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retirement_plans', to='operations.operatingissue')),
                ('operating_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retirement_plans', to='operations.operatingdatasnapshot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retirement_plans', to='products.productasset')),
            ],
            options={
                'db_table': 'operations_retirement_plan',
            },
        ),
        migrations.CreateModel(
            name='RetirementExecutionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('STOP_PRODUCTION', 'Stop production'), ('STOP_SALE', 'Stop sale'), ('RETIRE', 'Retire')], max_length=32)),
                ('scheduled_for', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_actions', to='operations.retirementplan')),
            ],
            options={
                'db_table': 'operations_retirement_execution_action',
            },
        ),
        migrations.AddIndex(
            model_name='retirementplan',
            index=models.Index(fields=['organization', 'product', 'status'], name='ops_retire_plan_product_idx'),
        ),
        migrations.AddIndex(
            model_name='retirementexecutionaction',
            index=models.Index(fields=['organization', 'status', 'scheduled_for'], name='ops_retire_action_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='retirementexecutionaction',
            constraint=models.UniqueConstraint(fields=('plan', 'action_type'), name='operations_retirement_action_type_uniq'),
        ),
    ]
