# Generated by Django 5.2.15 on 2026-08-03 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_employee_no_unique_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('INTERNAL_ACCEPTANCE', 'Internal acceptance'), ('BUSINESS_PILOT', 'Business pilot')], default='INTERNAL_ACCEPTANCE', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=16)),
                ('planned_participant_count', models.PositiveSmallIntegerField(default=8)),
                ('planned_duration_days', models.PositiveSmallIntegerField(default=14)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('data_scope_note', models.CharField(blank=True, max_length=512)),
                ('feedback_owner_note', models.CharField(blank=True, max_length=255)),
                ('known_limits_note', models.TextField(blank=True)),
                ('stop_conditions_note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pilot_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'pilot_batch',
            },
        ),
        migrations.CreateModel(
            name='PilotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('reproduction_summary', models.CharField(max_length=1024)),
                ('severity', models.CharField(blank=True, choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In progress'), ('READY_FOR_RETEST', 'Ready for retest'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=32)),
                ('external_key', models.CharField(blank=True, default='', max_length=128)),
                ('external_key_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evidence_document_version_public_id', models.UUIDField(blank=True, null=True)),
                ('target_version', models.CharField(blank=True, max_length=64)),
                ('workaround', models.TextField(blank=True)),
                ('acceptance_note', models.CharField(blank=True, max_length=512)),
                ('close_reason', models.CharField(blank=True, max_length=255)),
                ('retest_result', models.CharField(blank=True, max_length=32)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_pilot_feedback', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_pilot_feedback', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_items', to='pilot.pilotbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_pilot_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilot_feedback',
            },
        ),
        migrations.CreateModel(
            name='PilotParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name_snapshot', models.CharField(max_length=128)),
                ('employee_no_snapshot', models.CharField(blank=True, max_length=64)),
                ('department_snapshot', models.CharField(blank=True, max_length=128)),
                ('role_codes_snapshot', models.JSONField(blank=True, default=list)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='pilot.pilotbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilot_participant',
            },
        ),
        migrations.AddIndex(
            model_name='pilotbatch',
            index=models.Index(fields=['organization', 'status'], name='pilot_batch_organiz_c96409_idx'),
        ),
        migrations.AddIndex(
            model_name='pilotfeedback',
            index=models.Index(fields=['batch', 'status'], name='pilot_feedb_batch_i_ca66ed_idx'),
        ),
        migrations.AddIndex(
            model_name='pilotfeedback',
            index=models.Index(fields=['batch', 'severity'], name='pilot_feedb_batch_i_084b37_idx'),
        ),
        migrations.AddConstraint(
            model_name='pilotfeedback',
            constraint=models.UniqueConstraint(fields=('batch', 'external_key', 'external_key_slot'), name='pilot_feedback_batch_external_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pilotparticipant',
            constraint=models.UniqueConstraint(fields=('batch', 'user'), name='pilot_participant_batch_user_uniq'),
        ),
    ]
