# Generated by Django 5.2.15 on 2026-07-07 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('acting_roles_snapshot', models.JSONField(default=list)),
                ('action_code', models.CharField(max_length=128)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_public_id', models.UUIDField(blank=True, null=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=16)),
                ('before_summary', models.JSONField(default=dict)),
                ('after_summary', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('trace_id', models.CharField(max_length=64)),
                ('request_metadata', models.JSONField(default=dict)),
                ('related_snapshot_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events_as_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_audit_event',
                'indexes': [models.Index(fields=['occurred_at'], name='audit_audit_occurre_567fef_idx'), models.Index(fields=['action_code', 'occurred_at'], name='audit_audit_action__ee5d44_idx'), models.Index(fields=['resource_type', 'resource_public_id'], name='audit_audit_resourc_9ec395_idx')],
            },
        ),
    ]
