# Generated by Django 5.2.15 on 2026-07-07 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=128, unique=True)),
                ('resource_type', models.CharField(max_length=64)),
                ('action_category', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('DECIDE', 'Decide'), ('ADMIN', 'Admin'), ('EXPORT', 'Export')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authorization_permission_action',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role_type', models.CharField(choices=[('PLATFORM', 'Platform'), ('BUSINESS', 'Business')], max_length=16)),
                ('is_critical', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authorization_role',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scope_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('DEPARTMENT', 'Department'), ('PRODUCT_SET', 'Product set')], max_length=32)),
                ('scope_id', models.BigIntegerField(blank=True, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('approval_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configured_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='authorization.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authorization_role_assignment',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_data_level', models.CharField(choices=[('PUBLIC_SUMMARY', 'Public summary'), ('INTERNAL', 'Internal'), ('PROJECT_CONTROLLED', 'Project controlled'), ('SENSITIVE_CONTROLLED', 'Sensitive controlled'), ('HIGHLY_SENSITIVE', 'Highly sensitive')], max_length=32)),
                ('requires_object_scope', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='authorization.permissionaction')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='authorization.role')),
            ],
            options={
                'db_table': 'authorization_role_permission',
                'constraints': [models.UniqueConstraint(fields=('role', 'action'), name='authorization_role_action_uniq')],
            },
        ),
    ]
