# Generated by Django 5.2.15 on 2026-07-07 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('setting_key', models.CharField(max_length=64, unique=True)),
                ('dual_control_enabled', models.BooleanField(default=False)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authorization_security_setting',
            },
        ),
        migrations.CreateModel(
            name='AdminChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(max_length=64)),
                ('target_summary', models.JSONField(default=dict)),
                ('before_summary', models.JSONField(default=dict)),
                ('after_summary', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_admin_changes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_admin_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authorization_admin_change_request',
            },
        ),
        migrations.CreateModel(
            name='SpecialGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_public_id', models.UUIDField(blank=True, null=True)),
                ('actions', models.JSONField(default=list)),
                ('max_sensitivity_level', models.CharField(max_length=32)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=16)),
                ('purpose', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_grants', to=settings.AUTH_USER_MODEL)),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_special_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authorization_special_grant',
            },
        ),
        migrations.CreateModel(
            name='TroubleshootAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_public_id', models.UUIDField(blank=True, null=True)),
                ('actions', models.JSONField(default=list)),
                ('max_sensitivity_level', models.CharField(max_length=32)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('purpose', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_troubleshoot_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='troubleshoot_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authorization_troubleshoot_access',
            },
        ),
    ]
