# Generated by Django 5.2.15 on 2026-07-23 06:20

from django.conf import settings
from django.db import migrations, models


def seed_system_actor_provision_action(apps, schema_editor) -> None:
    permission_action = apps.get_model("authorization", "PermissionAction")
    permission_action.objects.get_or_create(
        action_code="system_actor.retirement.provision",
        defaults={
            "resource_type": "system_actor",
            "action_category": "ADMIN",
            "description": "Provision retirement system executor principal",
        },
    )


def unseed_system_actor_provision_action(apps, schema_editor) -> None:
    permission_action = apps.get_model("authorization", "PermissionAction")
    permission_action.objects.filter(
        action_code="system_actor.retirement.provision"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0008_seed_operations_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            seed_system_actor_provision_action,
            unseed_system_actor_provision_action,
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("effective_to__isnull", True), ("status", "ACTIVE")),
                fields=("user", "role", "scope_type", "scope_id"),
                name="authorization_role_assignment_active_scope_uniq",
            ),
        ),
    ]
