# Generated by Django 5.2.15 on 2026-07-23 08:07

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Min


def backfill_active_slot(apps, schema_editor) -> None:
    RoleAssignment = apps.get_model("authorization", "RoleAssignment")
    RoleAssignment.objects.exclude(status="ACTIVE", effective_to__isnull=True).update(
        active_slot=None
    )
    RoleAssignment.objects.filter(status="ACTIVE", effective_to__isnull=True).update(
        active_slot=1
    )
    duplicates = (
        RoleAssignment.objects.filter(active_slot=1)
        .values("user_id", "role_id", "scope_type", "scope_id")
        .annotate(n=Count("id"), keep_id=Min("id"))
        .filter(n__gt=1)
    )
    for row in duplicates:
        RoleAssignment.objects.filter(
            user_id=row["user_id"],
            role_id=row["role_id"],
            scope_type=row["scope_type"],
            scope_id=row["scope_id"],
            active_slot=1,
        ).exclude(id=row["keep_id"]).update(active_slot=None, status="INACTIVE")


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0009_provision_system_actor_and_assignment_uniq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="roleassignment",
            name="authorization_role_assignment_active_scope_uniq",
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="active_slot",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.RunPython(backfill_active_slot, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "role", "scope_type", "scope_id", "active_slot"),
                name="authorization_role_assignment_active_slot_uniq",
            ),
        ),
    ]
