"""Stable platform action codes for phase 1 APIs."""

from __future__ import annotations

from apps.authorization.models.role import ActionCategory

PLATFORM_ACTIONS: tuple[tuple[str, str, str], ...] = (
    ("identity.user.status_change", "identity.user", ActionCategory.ADMIN),
    ("authorization.role.read", "authorization.role", ActionCategory.READ),
    ("authorization.role.assign", "authorization.role", ActionCategory.ADMIN),
    (
        "authorization.admin_change.request",
        "authorization.admin_change_request",
        ActionCategory.ADMIN,
    ),
    (
        "authorization.admin_change.review",
        "authorization.admin_change_request",
        ActionCategory.ADMIN,
    ),
    (
        "authorization.troubleshoot.open",
        "authorization.troubleshoot_access",
        ActionCategory.ADMIN,
    ),
    ("audit.event.read", "audit.event", ActionCategory.READ),
    ("configuration.version.read", "configuration.version", ActionCategory.READ),
    ("configuration.version.publish", "configuration.version", ActionCategory.ADMIN),
    ("document.version.upload", "document.version", ActionCategory.WRITE),
    ("document.version.download", "document.version", ActionCategory.READ),
    ("notification.todo.read", "notification.todo", ActionCategory.READ),
)

OPPORTUNITY_ACTIONS: tuple[tuple[str, str, str], ...] = (
    ("opportunity.create", "opportunity", ActionCategory.WRITE),
    ("opportunity.edit", "opportunity", ActionCategory.WRITE),
    ("opportunity.submit", "opportunity", ActionCategory.WRITE),
    ("opportunity.withdraw", "opportunity", ActionCategory.WRITE),
    ("opportunity.full.read", "opportunity", ActionCategory.READ),
    ("opportunity.public_summary.read", "opportunity", ActionCategory.READ),
    ("opportunity.export", "opportunity", ActionCategory.EXPORT),
    ("opportunity.member.invite", "opportunity", ActionCategory.WRITE),
    ("opportunity.member.manage", "opportunity", ActionCategory.WRITE),
    ("candidate.create", "project_candidate", ActionCategory.WRITE),
    ("candidate.combine", "project_candidate", ActionCategory.WRITE),
    ("candidate.split", "project_candidate", ActionCategory.WRITE),
    ("candidate.leadership.assign", "project_candidate", ActionCategory.ADMIN),
    ("candidate.assessment.edit", "project_candidate", ActionCategory.WRITE),
    ("candidate.submit_review", "project_candidate", ActionCategory.WRITE),
    ("major_gate.management_conclusion.record", "stage_gate", ActionCategory.DECIDE),
    ("major_gate.final_decision.record", "stage_gate", ActionCategory.DECIDE),
    ("deferred_item.review", "opportunity", ActionCategory.DECIDE),
    ("reconsideration.create", "opportunity", ActionCategory.WRITE),
)

PRODUCT_ACTIONS: tuple[tuple[str, str, str], ...] = (
    ("product.search", "product", ActionCategory.READ),
    ("product.read_basic", "product", ActionCategory.READ),
    ("product.read_sensitive", "product", ActionCategory.READ),
    ("product_version.history.read", "product", ActionCategory.READ),
    ("product_draft.create", "product_change_set", ActionCategory.WRITE),
    ("product_draft.edit_group", "product_change_set", ActionCategory.WRITE),
    ("product_draft.submit", "product_change_set", ActionCategory.DECIDE),
    ("product_change_set.approve", "product_change_set", ActionCategory.DECIDE),
    ("attribute_group.confirm", "product_change_set", ActionCategory.DECIDE),
    ("attribute_group.return", "product_change_set", ActionCategory.DECIDE),
    ("confirmer.reassign", "product_change_set", ActionCategory.ADMIN),
    ("product.publish_new", "product", ActionCategory.DECIDE),
    ("product.publish_iteration", "product", ActionCategory.DECIDE),
    ("product.publish_baseline", "product", ActionCategory.DECIDE),
    ("product.correct_baseline", "product", ActionCategory.DECIDE),
    ("product_material.preview", "product_material", ActionCategory.READ),
    ("product_material.download_original", "product_material", ActionCategory.READ),
    ("product.export", "product", ActionCategory.EXPORT),
    ("external_binding.manage", "product", ActionCategory.ADMIN),
    ("migration.upload", "migration", ActionCategory.ADMIN),
    ("migration.review", "migration", ActionCategory.ADMIN),
    ("migration.confirm", "migration", ActionCategory.ADMIN),
)

EXECUTION_ACTIONS: tuple[tuple[str, str, str], ...] = (
    ("project.read", "project", ActionCategory.READ),
    ("plan.edit", "project", ActionCategory.WRITE),
    ("member.manage", "project", ActionCategory.ADMIN),
    ("task.create", "task", ActionCategory.WRITE),
    ("task.assign_department_member", "task", ActionCategory.WRITE),
    ("task.update_own", "task", ActionCategory.WRITE),
    ("deliverable.create", "deliverable", ActionCategory.WRITE),
    ("revision.submit", "deliverable_revision", ActionCategory.WRITE),
    ("revision.download", "deliverable_revision", ActionCategory.READ),
    ("professional_confirmation.decide", "professional_confirmation", ActionCategory.DECIDE),
    ("confirmer.reassign", "product_change_set", ActionCategory.ADMIN),
    ("stage_handling.request", "project_stage", ActionCategory.WRITE),
    ("stage_handling.confirm", "project_stage", ActionCategory.DECIDE),
    ("stage_gate.submit", "stage_gate", ActionCategory.WRITE),
    ("normal_gate.decide", "stage_gate", ActionCategory.DECIDE),
    ("first_launch.management_conclusion.record", "stage_gate", ActionCategory.DECIDE),
    ("first_launch.final_decision.record", "stage_gate", ActionCategory.DECIDE),
    ("project_exception.confirm", "project", ActionCategory.DECIDE),
    ("plan_change.apply_minor", "project", ActionCategory.WRITE),
    ("plan_change.confirm_important", "project", ActionCategory.DECIDE),
    ("emergency_execution.create", "project", ActionCategory.WRITE),
    ("emergency_execution.complete", "project", ActionCategory.WRITE),
    ("project_migration.confirm", "project", ActionCategory.ADMIN),
    ("project.publish_repair", "project", ActionCategory.WRITE),
)

OPERATIONS_ACTIONS: tuple[tuple[str, str, str], ...] = (
    ("operating_fact.read", "operating_fact", ActionCategory.READ),
    ("operating_detail.export", "operating_fact", ActionCategory.EXPORT),
    ("data_source.configure", "data_source", ActionCategory.ADMIN),
    ("ingestion_batch.create", "ingestion_batch", ActionCategory.WRITE),
    ("ingestion_batch.confirm", "ingestion_batch", ActionCategory.WRITE),
    ("ingestion_batch.retry", "ingestion_batch", ActionCategory.WRITE),
    ("mapping.resolve", "ingestion_batch", ActionCategory.WRITE),
    ("monitoring_scope.manage", "monitoring_scope", ActionCategory.ADMIN),
    ("manual_effective_value.create", "operating_value", ActionCategory.WRITE),
    ("manual_effective_value.modify", "operating_value", ActionCategory.WRITE),
    ("manual_effective_value.revoke", "operating_value", ActionCategory.WRITE),
    ("risk_signal.read", "risk_signal", ActionCategory.READ),
    ("risk_signal.close", "risk_signal", ActionCategory.WRITE),
    ("risk_signal.escalate", "risk_signal", ActionCategory.WRITE),
    ("operating_issue.create", "operating_issue", ActionCategory.WRITE),
    ("operating_issue.analyze", "operating_issue", ActionCategory.WRITE),
    ("operating_issue.close", "operating_issue", ActionCategory.WRITE),
    ("iteration_proposal.convert", "operating_issue", ActionCategory.WRITE),
    ("retirement_plan.create", "retirement_plan", ActionCategory.WRITE),
    ("retirement_plan.submit", "retirement_plan", ActionCategory.WRITE),
    ("retirement_plan.execute", "retirement_plan", ActionCategory.WRITE),
    ("retirement.management_conclusion.record", "stage_gate", ActionCategory.DECIDE),
    ("retirement.final_decision.record", "stage_gate", ActionCategory.DECIDE),
    ("metric_rule.configure", "metric_definition", ActionCategory.ADMIN),
)
