# Generated by Django 5.2.15 on 2026-07-10 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_system', models.CharField(max_length=40)),
                ('object_type', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=120)),
                ('internal_object_type', models.CharField(max_length=40)),
                ('internal_object_id', models.BigIntegerField()),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('binding_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'integrations_external_binding',
                'indexes': [models.Index(fields=['internal_object_type', 'internal_object_id'], name='integration_interna_231e45_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_system', 'object_type', 'external_id'), name='integrations_external_binding_uniq')],
            },
        ),
    ]
