# Generated by Django 5.2.15 on 2026-07-21 01:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_seed_operating_source_mapping_definition'),
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('integrations', '0001_external_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('API', 'API'), ('FILE', 'File'), ('MANUAL', 'Manual')], max_length=16)),
                ('sensitivity_level', models.CharField(choices=[('PUBLIC_SUMMARY', 'Public summary'), ('INTERNAL', 'Internal'), ('PROJECT_CONTROLLED', 'Project controlled'), ('SENSITIVE_CONTROLLED', 'Sensitive controlled'), ('HIGHLY_SENSITIVE', 'Highly sensitive')], default='INTERNAL', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_data_sources', to='configuration.configurationversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('owner_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_data_sources', to='identity.department')),
            ],
            options={
                'db_table': 'integrations_data_source',
                'indexes': [models.Index(fields=['organization', 'status', 'source_type'], name='integration_organiz_181454_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_code'), name='integrations_data_source_org_code_uniq')],
            },
        ),
    ]
