# Generated by Django 5.2.15 on 2026-07-21 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_upload_session_document_version'),
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('integrations', '0002_operating_data_sources'),
        ('operations', '0002_monitoring_assignments_metric_definitions'),
        ('products', '0010_attribute_group_assigned_confirmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('batch_key', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('API', 'API'), ('FILE', 'File'), ('MANUAL', 'Manual')], max_length=16)),
                ('business_period_from', models.DateField(blank=True, null=True)),
                ('business_period_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATING', 'Validating'), ('READY', 'Ready'), ('IMPORTING', 'Importing'), ('PARTIAL_SUCCESS', 'Partial success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RECEIVED', max_length=24)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('added_count', models.PositiveIntegerField(default=0)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('confirm_idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ingestion_batches', to=settings.AUTH_USER_MODEL)),
                ('input_file_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operating_ingestion_batches', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_batches', to='integrations.datasource')),
            ],
            options={
                'db_table': 'integrations_ingestion_batch',
            },
        ),
        migrations.CreateModel(
            name='IngestionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('row_number', models.PositiveIntegerField()),
                ('external_record_key', models.CharField(blank=True, default='', max_length=128)),
                ('raw_payload', models.JSONField(default=dict)),
                ('sku_code', models.CharField(blank=True, default='', max_length=64)),
                ('channel_code', models.CharField(blank=True, default='', max_length=64)),
                ('metric_code', models.CharField(blank=True, default='', max_length=64)),
                ('period_granularity', models.CharField(blank=True, default='', max_length=12)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('UNMAPPED', 'Unmapped'), ('IMPORTED', 'Imported'), ('SKIPPED', 'Skipped')], default='VALID', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('warning_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='integrations.ingestionbatch')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_rows', to='products.channelconfiguration')),
                ('metric_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_rows', to='operations.metricdefinitionversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_rows', to='products.sku')),
            ],
            options={
                'db_table': 'integrations_ingestion_row',
            },
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='integration_organiz_92ae49_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestionbatch',
            constraint=models.UniqueConstraint(fields=('source', 'batch_key'), name='integrations_ingestion_batch_source_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='ingestionrow',
            index=models.Index(fields=['batch', 'status'], name='integration_batch_i_c4a303_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionrow',
            index=models.Index(fields=['batch', 'external_record_key'], name='integration_batch_i_fcc4f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestionrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='integrations_ingestion_row_batch_num_uniq'),
        ),
    ]
