# Generated by Django 5.2.15 on 2026-07-07 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('document_code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(choices=[('PROJECT', 'Project'), ('PRODUCT', 'Product'), ('MIGRATION', 'Migration'), ('INTEGRATION', 'Integration')], max_length=16)),
                ('default_sensitivity_level', models.CharField(default='INTERNAL', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VOIDED', 'Voided'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'documents_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('declared_mime_type', models.CharField(max_length=128)),
                ('detected_mime_type', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked'), ('CONTROLLED', 'Controlled'), ('RETURNED', 'Returned'), ('VOIDED', 'Voided')], default='DRAFT', max_length=16)),
                ('sensitivity_level', models.CharField(default='INTERNAL', max_length=32)),
                ('uploaded_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('controlled_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('supersedes_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.documentversion')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_versions_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document_version',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion'),
        ),
        migrations.CreateModel(
            name='DownloadTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('PREVIEW', 'Preview'), ('DOWNLOAD', 'Download')], max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_download_ticket',
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('storage_backend', models.CharField(choices=[('NAS_NFS', 'NAS NFS')], default='NAS_NFS', max_length=16)),
                ('object_key', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('detected_mime_type', models.CharField(max_length=128)),
                ('storage_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('MISSING', 'Missing'), ('QUARANTINED', 'Quarantined')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'documents_file_object',
            },
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.fileobject'),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('temp_path', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=255)),
                ('declared_mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_upload_session',
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('linked_type', models.CharField(max_length=64)),
                ('linked_id', models.UUIDField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_document_link',
                'indexes': [models.Index(fields=['linked_type', 'linked_id'], name='documents_d_linked__f4bf4c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('organization', 'document_code'), name='documents_document_org_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='fileobject',
            index=models.Index(fields=['storage_status', 'created_at'], name='documents_f_storage_1bb878_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='documents_version_doc_num_uniq'),
        ),
    ]
