# Generated by Django 5.2.15 on 2026-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_upload_session_document_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='catalog_item_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='catalog_content_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='catalog_item_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='catalog_version_public_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
