# Generated by Django 5.2.15 on 2026-07-07 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('definition_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'configuration_definition',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('content_json', models.JSONField(default=dict)),
                ('content_digest', models.CharField(blank=True, max_length=64)),
                ('scope_json', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('diff_summary', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_versions_created', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='configuration.configurationdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_versions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuration_version',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('content_copy', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('reference_type', models.CharField(max_length=64)),
                ('reference_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='configuration.configurationversion')),
            ],
            options={
                'db_table': 'configuration_snapshot',
            },
        ),
        migrations.AddConstraint(
            model_name='configurationdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'definition_code'), name='configuration_definition_org_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='configurationversion',
            index=models.Index(fields=['definition', 'status'], name='configurati_definit_970f67_idx'),
        ),
        migrations.AddConstraint(
            model_name='configurationversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version_number'), name='configuration_version_def_num_uniq'),
        ),
        migrations.AddIndex(
            model_name='configurationsnapshot',
            index=models.Index(fields=['reference_type', 'reference_id'], name='configurati_referen_af10fd_idx'),
        ),
    ]
