# Generated by Django 5.2.15 on 2026-07-08 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_no', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('public_summary', models.TextField(blank=True, default='')),
                ('initial_type', models.CharField(choices=[('NEW', 'New product'), ('ITERATION', 'Product iteration'), ('UNDECIDED', 'Undecided')], default='UNDECIDED', max_length=32)),
                ('quota_owner_type', models.CharField(choices=[('USER', 'User'), ('DEPARTMENT', 'Department')], max_length=16)),
                ('quota_owner_id', models.BigIntegerField()),
                ('proposal_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('NEEDS_INFO', 'Needs info'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed'), ('CASE_APPROVED', 'Case approved')], default='DRAFT', max_length=32)),
                ('visibility_level', models.CharField(choices=[('PUBLIC_SUMMARY', 'Public summary'), ('INTERNAL', 'Internal'), ('PROJECT_CONTROLLED', 'Project controlled'), ('SENSITIVE_CONTROLLED', 'Sensitive controlled'), ('HIGHLY_SENSITIVE', 'Highly sensitive')], default='INTERNAL', max_length=32)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='identity.department')),
                ('proposal_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunities_opportunity',
            },
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('version_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('market_analysis', models.TextField(blank=True, default='')),
                ('core_selling_points', models.TextField(blank=True, default='')),
                ('target_users_needs', models.TextField(blank=True, default='')),
                ('suggested_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('content_snapshot', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'opportunities_proposal_version',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='opportunities.proposalversion'),
        ),
        migrations.CreateModel(
            name='QuotaLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quarter', models.CharField(max_length=8)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('DEPARTMENT', 'Department')], max_length=16)),
                ('owner_id', models.BigIntegerField()),
                ('count_status', models.CharField(choices=[('COUNTED', 'Counted'), ('EXCLUDED', 'Excluded')], default='COUNTED', max_length=16)),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_entries', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'opportunities_quota_ledger',
            },
        ),
        migrations.CreateModel(
            name='SubmissionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quarter', models.CharField(max_length=8)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('DEPARTMENT', 'Department')], max_length=16)),
                ('owner_id', models.BigIntegerField()),
                ('minimum_count', models.PositiveIntegerField(default=0)),
                ('enforcement_mode', models.CharField(choices=[('BLOCK', 'Block submission'), ('WARN', 'Warn only')], default='WARN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_quotas', to='configuration.configurationversion')),
            ],
            options={
                'db_table': 'opportunities_submission_quota',
            },
        ),
        migrations.CreateModel(
            name='OpportunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('member_role', models.CharField(choices=[('OWNER', 'Owner'), ('COLLABORATOR', 'Collaborator')], max_length=20)),
                ('invitation_status', models.CharField(choices=[('INVITED', 'Invited'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='INVITED', max_length=20)),
                ('active_from', models.DateTimeField()),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('contribution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunities_opportunity_member',
                'indexes': [models.Index(fields=['opportunity', 'member_role'], name='opportuniti_opportu_52a9ff_idx'), models.Index(fields=['user', 'invitation_status'], name='opportuniti_user_id_252d5d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active_to__isnull', True)), fields=('opportunity', 'user', 'member_role'), name='opportunities_member_active_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='proposalversion',
            index=models.Index(fields=['opportunity', 'version_status'], name='opportuniti_opportu_a999f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.UniqueConstraint(fields=('opportunity', 'version_number'), name='opportunities_proposal_version_num_uniq'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organization', 'proposal_status', 'updated_at'], name='opportuniti_organiz_5c2e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['proposal_owner', 'proposal_status'], name='opportuniti_proposa_c16d10_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['quota_owner_type', 'quota_owner_id', 'created_at'], name='opportuniti_quota_o_a559f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.UniqueConstraint(fields=('organization', 'business_no'), name='opportunities_opportunity_org_no_uniq'),
        ),
        migrations.AddIndex(
            model_name='quotaledger',
            index=models.Index(fields=['owner_type', 'owner_id', 'quarter'], name='opportuniti_owner_t_887fa1_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotaledger',
            constraint=models.UniqueConstraint(fields=('opportunity',), name='opportunities_quota_ledger_opportunity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submissionquota',
            constraint=models.UniqueConstraint(fields=('organization', 'quarter', 'owner_type', 'owner_id'), name='opportunities_submission_quota_uniq'),
        ),
    ]
