# Generated by Django 5.2.15 on 2026-07-08 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_no', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('candidate_type', models.CharField(choices=[('NEW_PRODUCT', 'New product'), ('PRODUCT_CHANGE', 'Product change')], default='NEW_PRODUCT', max_length=20)),
                ('target_product_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AWAITING_ASSIGNMENT', 'Awaiting assignment'), ('ASSESSING', 'Assessing'), ('IN_PROJECT_REVIEW', 'In project review'), ('NEEDS_INFO', 'Needs info'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed'), ('PROJECT_CREATED', 'Project created')], default='AWAITING_ASSIGNMENT', max_length=32)),
                ('proposed_schedule', models.JSONField(blank=True, default=dict)),
                ('resource_risk_summary', models.TextField(blank=True, default='')),
                ('project_id', models.BigIntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_case_candidates', to=settings.AUTH_USER_MODEL)),
                ('deputy_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deputy_case_candidates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'opportunities_project_candidate',
            },
        ),
        migrations.CreateModel(
            name='CaseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('category_code', models.CharField(choices=[('PRODUCTION_PARTY', 'Production party'), ('COOPERATION', 'Cooperation'), ('FACTORY', 'Factory'), ('PROCESS', 'Process'), ('RAW_PACKAGING', 'Raw and packaging'), ('COST', 'Cost'), ('SCHEDULE', 'Schedule'), ('RISK', 'Risk')], max_length=32)),
                ('conclusion', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('READY', 'Ready'), ('CONFIRMED', 'Confirmed'), ('EXEMPTED', 'Exempted')], default='NOT_STARTED', max_length=16)),
                ('deliverable_version_public_id', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='opportunities.projectcandidate')),
            ],
            options={
                'db_table': 'opportunities_case_assessment',
            },
        ),
        migrations.CreateModel(
            name='CandidateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('ADDITIONAL', 'Additional')], default='PRIMARY', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField()),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_candidate_sources', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_links', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='opportunities.projectcandidate')),
            ],
            options={
                'db_table': 'opportunities_candidate_source',
            },
        ),
        migrations.AddIndex(
            model_name='projectcandidate',
            index=models.Index(fields=['organization', 'status', 'updated_at'], name='opportuniti_organiz_0ddfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcandidate',
            index=models.Index(fields=['case_owner', 'status'], name='opportuniti_case_ow_ce5003_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcandidate',
            constraint=models.UniqueConstraint(fields=('organization', 'business_no'), name='opportunities_candidate_org_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('project_id__isnull', False)), fields=('project_id',), name='opportunities_candidate_project_uniq'),
        ),
        migrations.AddConstraint(
            model_name='caseassessment',
            constraint=models.UniqueConstraint(fields=('candidate', 'category_code'), name='opportunities_assessment_cat_uniq'),
        ),
        migrations.AddIndex(
            model_name='candidatesource',
            index=models.Index(fields=['opportunity', 'is_active'], name='opportuniti_opportu_df3aab_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatesource',
            constraint=models.UniqueConstraint(fields=('candidate', 'opportunity'), name='opportunities_candidate_source_uniq'),
        ),
    ]
