# Generated by Django 5.2.15 on 2026-07-09 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0002_projectcandidate_caseassessment_candidatesource_and_more'),
        ('stage_gates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcandidate',
            name='status',
            field=models.CharField(choices=[('AWAITING_ASSIGNMENT', 'Awaiting assignment'), ('ASSESSING', 'Assessing'), ('IN_PROJECT_REVIEW', 'In project review'), ('NEEDS_INFO', 'Needs info'), ('DEFERRED', 'Deferred'), ('PASSED', 'Passed'), ('SOURCE_RECONFIRM_REQUIRED', 'Source reconfirm required'), ('PROJECT_CREATED', 'Project created')], default='AWAITING_ASSIGNMENT', max_length=32),
        ),
        migrations.CreateModel(
            name='DeferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject_type', models.CharField(max_length=32)),
                ('subject_public_id', models.UUIDField()),
                ('stage_code', models.CharField(max_length=32)),
                ('last_conclusion', models.CharField(blank=True, default='', max_length=32)),
                ('defer_reason', models.TextField(blank=True, default='')),
                ('restart_trigger', models.TextField(blank=True, default='')),
                ('next_review_quarter', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunities_defer_record',
            },
        ),
        migrations.CreateModel(
            name='DeferReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CONTINUE_DEFERRED', 'Continue deferred'), ('RESTART_REVIEW', 'Restart review'), ('CONVERT_TO_PASS', 'Convert to pass'), ('UPDATE_TRIGGER', 'Update trigger')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('new_restart_trigger', models.TextField(blank=True, default='')),
                ('new_next_review_quarter', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defer_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_entries', to='opportunities.deferrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('resulting_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defer_review_entries', to='stage_gates.stagegateinstance')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunities_defer_review_entry',
            },
        ),
        migrations.CreateModel(
            name='Reconsideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('subject_type', models.CharField(max_length=32)),
                ('original_subject_public_id', models.UUIDField()),
                ('target_stage_code', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('eligibility_basis', models.CharField(blank=True, default='', max_length=64)),
                ('adjustment_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconsiderations_started', to=settings.AUTH_USER_MODEL)),
                ('new_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconsiderations_as_new', to='stage_gates.stagegateinstance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('original_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconsiderations_as_original', to='stage_gates.stagegateinstance')),
            ],
            options={
                'db_table': 'opportunities_reconsideration',
            },
        ),
        migrations.AddIndex(
            model_name='deferrecord',
            index=models.Index(fields=['subject_type', 'subject_public_id', 'status'], name='opportuniti_subject_02ed4f_idx'),
        ),
        migrations.AddIndex(
            model_name='deferrecord',
            index=models.Index(fields=['organization', 'status', 'next_review_quarter'], name='opportuniti_organiz_eb2015_idx'),
        ),
        migrations.AddIndex(
            model_name='deferreviewentry',
            index=models.Index(fields=['defer_record', 'created_at'], name='opportuniti_defer_r_5707f9_idx'),
        ),
        migrations.AddIndex(
            model_name='reconsideration',
            index=models.Index(fields=['subject_type', 'original_subject_public_id'], name='opportuniti_subject_ce2603_idx'),
        ),
    ]
