# Generated by Django 5.2.15 on 2026-07-09 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0003_alter_projectcandidate_status_deferrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectcandidate',
            name='opportunities_candidate_project_uniq',
        ),
        migrations.AddConstraint(
            model_name='projectcandidate',
            constraint=models.UniqueConstraint(fields=('project_id',), name='opportunities_candidate_project_uniq'),
        ),
    ]
