# Generated by Django 5.2.15 on 2026-07-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_remove_projectcandidate_opportunities_candidate_project_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opportunitymember',
            name='opportunities_member_active_uniq',
        ),
        migrations.AddField(
            model_name='opportunitymember',
            name='active_membership_key',
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
    ]
