# Generated by Django 5.2.15 on 2026-07-09 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('draft_type', models.CharField(choices=[('NEW_PRODUCT', 'New product'), ('PRODUCT_CHANGE', 'Product change')], max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked')], default='DRAFT', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('definition_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products_product_draft',
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_no', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('NEW_PROJECT', 'New project'), ('LEGACY_IMPORT', 'Legacy import')], default='NEW_PROJECT', max_length=24)),
                ('lifecycle_status', models.CharField(choices=[('DEVELOPING', 'Developing'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired')], default='DEVELOPING', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_product_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products_product_asset',
            },
        ),
    ]
