# Generated by Django 5.2.15 on 2026-07-09 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0003_alter_projectcandidate_status_deferrecord_and_more'),
        ('products', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasset',
            name='source_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sourced_product_assets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='productdraft',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='productdraft',
            name='product_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='products.productasset'),
        ),
        migrations.AddField(
            model_name='productdraft',
            name='project_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_drafts', to='opportunities.projectcandidate'),
        ),
        migrations.AddField(
            model_name='productdraft',
            name='target_product_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_drafts', to='products.productasset'),
        ),
        migrations.AddIndex(
            model_name='productasset',
            index=models.Index(fields=['organization', 'lifecycle_status', 'updated_at'], name='products_pr_organiz_09d48e_idx'),
        ),
        migrations.AddIndex(
            model_name='productasset',
            index=models.Index(fields=['product_owner', 'lifecycle_status'], name='products_pr_product_cf962c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productasset',
            constraint=models.UniqueConstraint(fields=('organization', 'business_no'), name='products_asset_org_no_uniq'),
        ),
        migrations.AddIndex(
            model_name='productdraft',
            index=models.Index(fields=['product_asset', 'status'], name='products_pr_product_81d130_idx'),
        ),
        migrations.AddConstraint(
            model_name='productdraft',
            constraint=models.UniqueConstraint(fields=('project_candidate',), name='products_draft_candidate_uniq'),
        ),
    ]
