# Generated by Django 5.2.15 on 2026-07-10 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('products', '0004_product_change_set_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_product_change_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productchangeset',
            name='version_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AttributeGroupDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('group_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('owner_level', models.CharField(choices=[('PRODUCT', 'Product'), ('VERSION', 'Version'), ('SKU', 'SKU'), ('CHANNEL', 'Channel')], max_length=16)),
                ('department_code', models.CharField(blank=True, default='', max_length=40)),
                ('is_critical', models.BooleanField(default=False)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('sensitivity_level', models.CharField(default='INTERNAL', max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'products_attribute_group_definition',
            },
        ),
        migrations.CreateModel(
            name='AttributeSchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('schema_code', models.CharField(max_length=64)),
                ('version_number', models.PositiveIntegerField()),
                ('category_code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'products_attribute_schema_version',
            },
        ),
        migrations.CreateModel(
            name='AttributeGroupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('owner_type', models.CharField(choices=[('PRODUCT', 'Product'), ('VERSION', 'Version'), ('SKU', 'SKU'), ('CHANNEL', 'Channel')], max_length=16)),
                ('owner_id', models.BigIntegerField()),
                ('values_json', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('value_status', models.CharField(choices=[('DRAFT', 'Draft'), ('EFFECTIVE', 'Effective'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_group_values', to='products.productchangeset')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_attribute_group_values', to=settings.AUTH_USER_MODEL)),
                ('group_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='products.attributegroupdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_values', to='products.attributeschemaversion')),
            ],
            options={
                'db_table': 'products_attribute_group_value',
            },
        ),
        migrations.AddField(
            model_name='attributegroupdefinition',
            name='schema_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_definitions', to='products.attributeschemaversion'),
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('field_code', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('MONEY', 'Money'), ('DATE', 'Date'), ('SINGLE_SELECT', 'Single select'), ('MULTI_SELECT', 'Multi select'), ('BOOLEAN', 'Boolean'), ('USER_REF', 'User reference'), ('DEPARTMENT_REF', 'Department reference'), ('OBJECT_REF', 'Object reference'), ('FILE_REF', 'File reference'), ('IMAGE_REF', 'Image reference'), ('DETAIL_TABLE', 'Detail table')], max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('dictionary_code', models.CharField(blank=True, default='', max_length=64)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('sensitivity_level', models.CharField(default='INTERNAL', max_length=32)),
                ('searchable', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('group_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_definitions', to='products.attributegroupdefinition')),
            ],
            options={
                'db_table': 'products_attribute_definition',
                'indexes': [models.Index(fields=['group_definition', 'display_order'], name='products_at_group_d_4927f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('group_definition', 'field_code'), name='products_attr_def_group_code_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='attributeschemaversion',
            index=models.Index(fields=['organization', 'category_code', 'status'], name='products_at_organiz_1bca82_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributeschemaversion',
            constraint=models.UniqueConstraint(fields=('organization', 'schema_code', 'version_number'), name='products_schema_org_code_ver_uniq'),
        ),
        migrations.AddIndex(
            model_name='attributegroupvalue',
            index=models.Index(fields=['owner_type', 'owner_id', 'value_status'], name='products_at_owner_t_f79d48_idx'),
        ),
        migrations.AddIndex(
            model_name='attributegroupvalue',
            index=models.Index(fields=['change_set', 'value_status'], name='products_at_change__6b36d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributegroupvalue',
            constraint=models.UniqueConstraint(fields=('change_set', 'group_definition'), name='products_attr_value_change_group_uniq'),
        ),
        migrations.AddIndex(
            model_name='attributegroupdefinition',
            index=models.Index(fields=['schema_version', 'display_order'], name='products_at_schema__ced75f_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributegroupdefinition',
            constraint=models.UniqueConstraint(fields=('schema_version', 'group_code'), name='products_attr_group_schema_code_uniq'),
        ),
    ]
