# Generated by Django 5.2.15 on 2026-07-10 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('products', '0005_attribute_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('RETURNED', 'Returned')], max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField()),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_confirmations', to='products.productchangeset')),
                ('confirmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_confirmations', to=settings.AUTH_USER_MODEL)),
                ('group_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='products.attributegroupvalue')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'products_attribute_confirmation',
            },
        ),
        migrations.CreateModel(
            name='NutritionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('basis', models.CharField(choices=[('PER_100G', 'Per 100g'), ('PER_100ML', 'Per 100ml'), ('PER_SERVING', 'Per serving')], max_length=24)),
                ('structured_summary_hash', models.CharField(max_length=64)),
                ('label_summary_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_tables', to='products.productchangeset')),
                ('label_document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_labels', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('product_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nutrition_tables', to='products.productversion')),
            ],
            options={
                'db_table': 'products_nutrition_table',
            },
        ),
        migrations.CreateModel(
            name='NutritionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nutrient_code', models.CharField(max_length=40)),
                ('amount_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('amount_unit', models.CharField(max_length=20)),
                ('nrv_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=24)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('nutrition_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.nutritiontable')),
            ],
            options={
                'db_table': 'products_nutrition_item',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('owner_type', models.CharField(choices=[('PRODUCT', 'Product'), ('VERSION', 'Version'), ('SKU', 'SKU'), ('CHANNEL', 'Channel')], max_length=16)),
                ('owner_id', models.BigIntegerField()),
                ('material_type', models.CharField(choices=[('INNER_PACKAGING', 'Inner packaging'), ('OUTER_PACKAGING', 'Outer packaging'), ('LABEL', 'Label'), ('DESIGN_SOURCE', 'Design source'), ('CHANNEL_IMAGE', 'Channel image'), ('APPROVED_PRINT', 'Approved print')], max_length=24)),
                ('purpose', models.CharField(blank=True, default='', max_length=120)),
                ('sensitivity_level', models.CharField(default='INTERNAL', max_length=32)),
                ('material_status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='products.productchangeset')),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='products.attributeconfirmation')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_materials', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'products_product_material',
            },
        ),
        migrations.AddIndex(
            model_name='attributeconfirmation',
            index=models.Index(fields=['change_set', 'decision'], name='products_at_change__a3b058_idx'),
        ),
        migrations.AddIndex(
            model_name='attributeconfirmation',
            index=models.Index(fields=['group_value', 'superseded_at'], name='products_at_group_v_9bd721_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritiontable',
            index=models.Index(fields=['change_set'], name='products_nu_change__5a8955_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritiontable',
            index=models.Index(fields=['product_version'], name='products_nu_product_8034d6_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionitem',
            index=models.Index(fields=['nutrition_table', 'display_order'], name='products_nu_nutriti_de63e2_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['owner_type', 'owner_id', 'material_status'], name='products_pr_owner_t_1c3806_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['change_set', 'material_type'], name='products_pr_change__267b26_idx'),
        ),
    ]
