# Generated by Django 5.2.15 on 2026-07-10 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_nutrition_materials_confirmations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_product_change_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productchangeset',
            name='publish_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
