# Generated by Django 5.2.15 on 2026-07-10 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0005_remove_opportunitymember_opportunities_member_active_uniq_and_more'),
        ('products', '0007_publish_fields'),
        ('projects', '0003_product_profile_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('template_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=24)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_digest', models.CharField(blank=True, default='', max_length=64)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('linked_count', models.PositiveIntegerField(default=0)),
                ('confirm_idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products_import_batch',
            },
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_row_digest', models.CharField(max_length=64)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('duplicate_candidates', models.JSONField(blank=True, default=list)),
                ('item_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('DUPLICATE_REVIEW', 'Duplicate review'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=24)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('CREATE', 'Create'), ('LINK', 'Link'), ('SKIP', 'Skip')], default='PENDING', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products_import_item',
            },
        ),
        migrations.RemoveConstraint(
            model_name='productchangeset',
            name='products_draft_candidate_uniq',
        ),
        migrations.AlterField(
            model_name='productchangeset',
            name='project_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_change_sets', to='opportunities.projectcandidate'),
        ),
        migrations.AddConstraint(
            model_name='productchangeset',
            constraint=models.UniqueConstraint(condition=models.Q(('project_candidate__isnull', False)), fields=('project_candidate',), name='products_draft_candidate_uniq'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_product_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='baseline_change_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_items', to='products.productchangeset'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.importbatch'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='target_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_items', to='products.productasset'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['organization', 'status', 'updated_at'], name='products_im_organiz_afbc61_idx'),
        ),
        migrations.AddIndex(
            model_name='importitem',
            index=models.Index(fields=['batch', 'item_status'], name='products_im_batch_i_f3b912_idx'),
        ),
        migrations.AddConstraint(
            model_name='importitem',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='products_import_item_batch_row_uniq'),
        ),
    ]
