# Generated by Django 5.2.15 on 2026-07-13 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_mysql_candidate_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroupvalue',
            name='assigned_confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_attribute_group_confirmations', to=settings.AUTH_USER_MODEL),
        ),
    ]
