# Generated by Django 5.2.15 on 2026-07-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_attribute_group_assigned_confirmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='production_status',
            field=models.CharField(choices=[('IN_PRODUCTION', 'In production'), ('STOPPED', 'Production stopped')], default='IN_PRODUCTION', max_length=24),
        ),
        migrations.AddField(
            model_name='sku',
            name='production_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
