# Generated by Django 5.2.15 on 2026-07-31 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_catalogued_upload_metadata'),
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('products', '0011_sku_production_status_sku_production_stopped_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyMaterialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('owner_type', models.CharField(choices=[('PRODUCT', 'Product'), ('VERSION', 'Version'), ('SKU', 'SKU'), ('CHANNEL', 'Channel')], max_length=16)),
                ('owner_id', models.BigIntegerField()),
                ('source_note', models.TextField(blank=True, default='')),
                ('original_file_date', models.DateField(blank=True, null=True)),
                ('sha256', models.CharField(max_length=64)),
                ('claimed_version', models.CharField(blank=True, default='', max_length=64)),
                ('claimed_effective_from', models.DateField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING_TRIAGE', 'Pending triage'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING_TRIAGE', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_material_submissions', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_material_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products_legacy_material_submission',
                'indexes': [models.Index(fields=['sha256'], name='products_le_sha256_07f1a4_idx'), models.Index(fields=['owner_type', 'owner_id', 'processing_status'], name='products_le_owner_t_ffd8f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='products_legacy_submission_idem_uniq')],
            },
        ),
    ]
