# Generated by Django 5.2.15 on 2026-07-31 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_catalogued_upload_metadata'),
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('products', '0013_governed_product_materials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legacymaterialsubmission',
            name='promoted_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promoted_from', to='products.productmaterial'),
        ),
        migrations.AddField(
            model_name='legacymaterialsubmission',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='legacymaterialsubmission',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacymaterialsubmission',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_legacy_material_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='current_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='source_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promoted_materials', to='products.legacymaterialsubmission'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='supersedes_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='products.productmaterial'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='version_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.UniqueConstraint(fields=('organization', 'owner_type', 'owner_id', 'material_type_code', 'current_slot'), name='products_material_current_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.UniqueConstraint(fields=('organization', 'owner_type', 'owner_id', 'material_type_code', 'version_no'), name='products_material_version_uniq'),
        ),
    ]
