# Generated by Django 5.2.15 on 2026-07-31 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_user_identity_user_org_employee_no_uniq_and_more'),
        ('opportunities', '0005_remove_opportunitymember_opportunities_member_active_uniq_and_more'),
        ('products', '0014_material_version_chain'),
        ('projects', '0011_migration_file_stage_relpath_len'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeset',
            name='draft_idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='productchangeset',
            constraint=models.UniqueConstraint(fields=('organization', 'draft_idempotency_key'), name='products_draft_idempotency_uniq'),
        ),
    ]
