# Generated by Django 5.2.15 on 2026-08-04 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_employee_no_unique_slot'),
        ('products', '0015_legacy_baseline_draft_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConfirmationSettlementRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('todo_public_id', models.UUIDField()),
                ('reissued_event_id', models.UUIDField()),
                ('reason', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_repairs', to='products.materialconfirmation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='identity.organization')),
            ],
            options={
                'db_table': 'products_material_confirmation_settlement_repair',
                'constraints': [models.UniqueConstraint(fields=('confirmation', 'todo_public_id'), name='products_material_repair_uniq')],
            },
        ),
    ]
