# Generated by Django 5.2.15 on 2026-07-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='identity_user_org_employee_no_uniq',
        ),
        migrations.AlterField(
            model_name='department',
            name='external_dingtalk_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_no', ''), _negated=True), fields=('organization', 'employee_no'), name='identity_user_org_employee_no_uniq'),
        ),
    ]
